feat: 로그인, 회원가입 페이지 유효성 검사 수정
kdt-final-3/salarying-fe pull request #61
Opened 2023-03-31 12:43 UTC by hyerani

## 작업 개요 (이슈 번호)

Close #54

## 작업 내용 (변경 사항)
- onChange 상태 일때 바로 유효성 검사 처리될 수 있도록 수정했습니다.
- required 유효성검사 수정, 상수 파일을 생성했습니다.
- 회사명, 대표자명 유효성 검사 추가 했습니다.
https://deploy-preview-59--jobkok.netlify.app/sign-up

## 리뷰 요청 사항

2023-03-31 12:56 UTC, hyorimcho commented
고생하셨어요 혜란님

PR 메세지의 링크 주소가 잘못되었어요!
deploy preview에도 번호가 있어서 이전 링크에 수정하면 안되고 새로운 주소를 붙여야 하는 것 같습니다 ㅎㅎ
비밀번호 눈뜨기의 경우 비밀번호 입력 창 중 한 군데에만 있어도 괜찮을 것 같은데 어떠신가요😃?

2023-03-31 13:46 UTC, eun0leee requested changes
혜란님!
여러가지 업데이트 하시느라 너무너무 고생 많으셨습니다ㅎㅎ
🌈🌈🌈

2023-03-31 13:46 UTC, eun0leee commented on src/pages/SignIn/index.tsx
>                {showPw.visible ? <span>눈감기</span> : <span>눈뜨기</span>}
비밀번호에 대한 눈감기를 누르면, 비밀번호와 비밀번호 재확인 둘 다 눈이 감겨집니다..!!!! 🤔
state 하나로 관리해서 그런 것 같습니당...!!!

2023-03-31 13:46 UTC, eun0leee approved these changes

2023-03-31 13:46 UTC, eun0leee approved these changes

2023-04-01 08:18 UTC, hyerani commented on src/pages/SignIn/index.tsx
>                {showPw.visible ? <span>눈감기</span> : <span>눈뜨기</span>}
비밀번호 입력, 재확인 입력 칸의 경우 맞지 않을 경우 눈뜨기를 두번 클릭 후 확인하는 것보다 하나만 눌러도 확인 가능하도록 둘다 보여지게 처리했습니당..!!

2023-04-01 14:46 UTC, merged

2023-04-02 02:28 UTC, yujiseok commented on src/pages/SignUp/index.tsx
>    });
회원가입, 로그인 페이지에서 똑같이 사용되니 커스텀 훅으로 만든는 것도 좋아보입니다!